apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine 
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "echo Hello from Alpine && sleep 3600"]
